# Generated by Django 5.2.3 on 2025-07-30 18:54

from django.db import migrations


def set_disable_ptr_false(apps, schema_editor):
    Record = apps.get_model("netbox_dns", "Record")

    Record.objects.filter(
        disable_ptr=True,
    ).exclude(
        type__in=("A", "AAAA"),
    ).update(
        disable_ptr=False,
    )


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_dns", "0022_alter_record_ipam_ip_address"),
    ]

    operations = [
        migrations.RunPython(
            set_disable_ptr_false,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
