# Generated by Django 6.0.7 on 2026-08-06 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("netbox_dns", "0032_record_expiration_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="external_rfc2317_zone",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rfc2317_static_cname_records",
                to="netbox_dns.zone",
            ),
        ),
    ]
